### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by gatomalaco**

### CODE REVIEW

**Comment by gatomalaco** [comment]
Spanish language files to be used in Battery Mode.

**Comment by gatomalaco** [comment]
Spanish language files to be used in Battery Mode.

**Comment by artar94** [comment]
@gatomalaco Have you closed this pull-request intentionally without merging because of some problems or you just hit "Close" button by mistake?

Is this translation ready to be included in Battery Mode?

**Comment by gatomalaco** [comment]
@artar94 Yeah I closed by mistake. If I have to re pull it its ok. The translation is ready to be included. Thank you for you really nice program.

**Comment by artar94** [comment]
@gatomalaco Thank you for the translation, there is no need to repull

**Comment by artar94** [comment]
@gatomalaco Today I have released Battery Mode 3.8.9.106 with Spanish translation included.
Thank you very much for your help!

**Comment by gatomalaco** [comment]
Excellent! I will check it out to see if there are some typos or somethign that doesnt make sense. If I make some modifications all I have to do is make a new pull request, right?

**Comment by artar94** [comment]
Yes, just do not forget to merge changes from main repository

**Pull request merged**
